### ISSUE TITLE
Getting an error while installing pip in hdp sandbox

### ISSUE THREAD

**Issue by merla** [AdharshAla/covid19_bigdata_project#1]
Hi,
I did go through your project..but when installing pip using command yum install pip , it gives me below error

http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos6/2.x/BUILDS/2.4.0.0-1225/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Error: Cannot retrieve repository metadata (repomd.xml) for repository: AMBARI.2.4.0.0-2.x. Please verify its path and try again

Any help in fixing this is appreciated

**Comment by Gorex-alt** [comment]
Can you tell me how you got around this error?

**Comment by merla** [comment]
The error is caused due to HDP sandbox version.I installed the latest version and got this error.Try installing Hortonworks HDP - 2.6.5 and this fixes the issue
